export const APP_VERSION = "v2.13.3-rare-recursionfix";
export const TABLE_NAME = "upper_michigan_foraging_species_v1";
export const FORAGING_RARE_SPECIES_TABLE = "foraging_rare_species_v1";
export const FORAGING_RARE_SIGHTINGS_TABLE = "foraging_rare_sightings_v1";
export const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];
export const MONTH_SHORT = MONTHS.map(month => month.slice(0,3));
export const PLANT_CATEGORIES = new Set(["Fruit","Green","Flower","Root","Tree Product","Green / Tubers"]);
export const ACTIVE_NOW_LABEL = "In season";
export const WEEKS = [1,2,3,4];
export const VOCAB_VERSION = "v2.13.3-rare-recursionfix";
