create table if not exists public.foraging_entries (
  id bigint generated by default as identity primary key,
  common_name text not null,
  scientific_name text,
  category text not null check (category in ('plant', 'mushroom')),
  season text,
  use_type text,
  edible_parts text,
  description text,
  notes text,
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.foraging_entries enable row level security;

create policy "Public can read foraging entries"
on public.foraging_entries
for select
using (true);

insert into public.foraging_entries
  (common_name, scientific_name, category, season, use_type, edible_parts, description, notes)
values
  ('Stinging Nettle', 'Urtica dioica', 'plant', 'early spring', 'culinary, medicinal', 'Young shoots and leaves', 'Harvest very young growth with gloves. Steam, sauté, or dry for tea.', 'Traditionally used for inflammation support. Handle carefully before cooking.'),
  ('Lamb''s Quarters', 'Chenopodium album', 'plant', 'late spring', 'culinary', 'Leaves and tender tops', 'Useful spinach substitute with tender leaves in spring and early summer.', 'Best collected young.'),
  ('Dandelion', 'Taraxacum officinale', 'plant', 'early spring', 'culinary, medicinal', 'Leaves, flowers, roots', 'Leaves for salads, roots for roasting or tea, flowers for fritters or wine.', 'Young leaves are less bitter.'),
  ('Cattail', 'Typha spp.', 'plant', 'late spring', 'culinary', 'Young shoots', 'Often called “cossack asparagus” when harvested young.', 'Harvest only from clean water areas.'),
  ('Paper Birch', 'Betula papyrifera', 'plant', 'early spring', 'culinary, medicinal', 'Sap', 'Sap can be tapped before leaf-out and consumed fresh or reduced.', 'Use tree-tapping best practices.'),
  ('Blueberry', 'Vaccinium angustifolium', 'plant', 'summer', 'culinary', 'Berries', 'A core Upper Michigan wild fruit with fresh and preserved uses.', 'A cornerstone guide entry.'),
  ('Thimbleberry', 'Rubus parviflorus', 'plant', 'summer', 'culinary', 'Berries', 'Soft red fruits that do not travel well, making them ideal for local field-guide use.', 'Best eaten quickly after harvest.'),
  ('Chokecherry', 'Prunus virginiana', 'plant', 'fall', 'culinary', 'Fruit', 'Strong, astringent fruit often used in jelly and syrup once fully ripe.', 'Processing usually improves flavor.'),
  ('Morel', 'Morchella spp.', 'mushroom', 'late spring', 'culinary', 'Fruiting body', 'One of the most sought-after spring mushrooms. Must always be cooked.', 'Do not confuse with false morels.'),
  ('Oyster Mushroom', 'Pleurotus ostreatus', 'mushroom', 'spring', 'culinary', 'Fruiting body', 'Fan-shaped mushroom often found on hardwood logs.', 'Normalize season value later.'),
  ('Chanterelle', 'Cantharellus spp.', 'mushroom', 'summer', 'culinary', 'Fruiting body', 'Golden, fruity, and worth a respectful frying pan.', 'A key mushroom already in project scope.'),
  ('Hen of the Woods', 'Grifola frondosa', 'mushroom', 'fall', 'culinary', 'Fruiting body', 'Clustered mushroom associated with hardwoods and cooler-season hunting.', 'Also known as maitake.')
on conflict do nothing;
