import { MONTHS, MONTH_SHORT } from "../constants-mainfix.js?v=v2.1-mainfix21";
import { isMushroom, isPlant, medicinalRecords } from "../data-model-mainfix4.js?v=v2.1-mainfix21";
import { renderResultCard } from "./cards-mainfix.js?v=v2.1-mainfix8";
import { escapeHtml } from "../utils.js?v=v2.0";

function recordsForMonth(records, month) { return records.filter(record => (record.months_available || []).includes(month)); }
function monthSummary(records, month) { const active = recordsForMonth(records, month); return { active, total: active.length, plants: active.filter(isPlant).length, mushrooms: active.filter(isMushroom).length, medicinal: medicinalRecords(active).length }; }
export function renderInteractiveTimeline(records, selectedMonth, paneMode = 'results') {
  const selected = monthSummary(records, selectedMonth);
  const selectedResults = selected.active.slice().sort((a, b) => a.display_name.localeCompare(b.display_name));
  const resultsHtml = selectedResults.length ? selectedResults.map(record => renderResultCard(record, 'general')).join('') : '<div class="panel empty-state"><h3>No entries in focus</h3><p>This month does not have imported activity yet.</p></div>';
  return `<section class="timeline-compact-shell"><article class="panel timeline-selector-card"><div class="timeline-toolbar"><div><p class="eyebrow subtle">Season rail</p><h3>${escapeHtml(selectedMonth)}</h3><p>Timeline now focuses on month-level periods only.</p></div><div class="focus-pills timeline-focus-pills"><span class="focus-pill plant">${selected.plants} plants</span><span class="focus-pill mushroom">${selected.mushrooms} mushrooms</span><span class="focus-pill medicinal">${selected.medicinal} medicinal</span></div></div><div class="timeline-window" aria-label="Month selector"><button class="timeline-shift-btn" type="button" data-action="timeline-shift" data-direction="prev" aria-label="Previous month">‹</button><div class="timeline-pill-viewport"><div class="timeline-pill-rail">${MONTHS.map((month, index) => `<button class="timeline-pill ${month === selectedMonth ? 'active' : ''}" type="button" data-timeline-month="${escapeHtml(month)}" aria-pressed="${month === selectedMonth ? 'true' : 'false'}"><span>${MONTH_SHORT[index]}</span></button>`).join('')}</div></div><button class="timeline-shift-btn" type="button" data-action="timeline-shift" data-direction="next" aria-label="Next month">›</button></div></article>${paneMode === 'filters' ? `<article class="panel workspace-pane filter-pane-card timeline-filter-pane"><div class="section-heading-block"><h3>Timeline filters</h3><p>Pick the month above to focus the season view.</p></div><div class="timeline-filter-summary-grid"><div><strong>${selected.total}</strong><span>Entries in ${escapeHtml(selectedMonth)}</span></div><div><strong>${selected.plants}</strong><span>Plant entries</span></div><div><strong>${selected.mushrooms}</strong><span>Mushroom entries</span></div><div><strong>${selected.medicinal}</strong><span>Medicinal entries</span></div></div></article>` : `<section class="panel workspace-pane results-pane-card timeline-results-panel"><div class="result-header compact-result-header"><div><h3>${escapeHtml(selectedMonth)}</h3><p class="results-meta">${selected.total} match${selected.total === 1 ? '' : 'es'}</p></div><a class="buttonish" href="#/review">Needs Review</a></div><div class="result-list">${resultsHtml}</div></section>`}</section>`;
}
