create table if not exists public.foraging_rare_species_v1 (
  id bigint generated by default as identity primary key,
  species_slug text unique not null,
  common_name text not null,
  scientific_name text not null,
  species_group text not null check (species_group in ('plant','fungus')),
  status_label text not null,
  legal_status text not null,
  up_relevance text,
  habitat text,
  rarity_reason text,
  sensitive_location boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.foraging_rare_sightings_v1 (
  id uuid primary key default gen_random_uuid(),
  species_slug text not null,
  species_name text not null,
  seen_on date not null,
  latitude numeric(9,6) not null,
  longitude numeric(9,6) not null,
  precision_mode text not null default 'approximate' check (precision_mode in ('exact','approximate','hidden')),
  notes text default '',
  source_app text default 'foraging',
  created_at timestamptz default now()
);

create index if not exists foraging_rare_sightings_v1_species_idx on public.foraging_rare_sightings_v1 (species_slug);
create index if not exists foraging_rare_sightings_v1_seen_on_idx on public.foraging_rare_sightings_v1 (seen_on desc);
