-- Upper Michigan Foraging Guide
-- Version: v0.2
-- Source workbooks: list with a few pics.xlsx, List of plants.xlsx

create table if not exists public.upper_michigan_foraging_species_v1 (
  species_id bigint generated by default as identity primary key,
  species_slug text not null unique,
  display_name text not null,
  common_name text not null,
  category text,
  culinary_uses text,
  medicinal_uses text,
  notes text,
  months_available text[] not null default '{}',
  source_links jsonb not null default '[]'::jsonb,
  image_paths jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_upper_michigan_foraging_species_v1_display_name
  on public.upper_michigan_foraging_species_v1 (display_name);
create index if not exists idx_upper_michigan_foraging_species_v1_category
  on public.upper_michigan_foraging_species_v1 (category);

alter table public.upper_michigan_foraging_species_v1 enable row level security;

drop policy if exists upper_michigan_foraging_species_v1_read_public on public.upper_michigan_foraging_species_v1;
create policy upper_michigan_foraging_species_v1_read_public
  on public.upper_michigan_foraging_species_v1
  for select
  to anon, authenticated
  using (true);

truncate table public.upper_michigan_foraging_species_v1 restart identity;

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('pine-needles-tea', 'Pine needles (tea)', 'Pine needles (tea)', 'Tree Product', 'Steeped as a vitamin C-rich tea', 'Immune support; respiratory relief', '', ARRAY['January','February','March','April','May','June','July','August','September','October','November','December']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('pine-resin-gum', 'Pine resin (gum)', 'Pine resin (gum)', 'Tree Product', 'Sap boiled into syrup or crystallized; resin and tips used in teas or chewed', 'Natural diuretic and tonic; antiseptic and mineral-rich', '', ARRAY['January','February','March','April','May','June','July','August','September','October','November','December']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('sassafras-root-bark', 'Sassafras root bark', 'Sassafras root bark', 'Tree Product', 'Used to flavor root beer or as filé powder', 'Traditional blood purifier; digestive tonic', '', ARRAY['January','February','March','April','May','June','July','August','September','October','November','December']::text[], '["https://burdockandrose.com/2022/10/03/foraging-sassafras-rootbeer/#:~:text=Sassafras%20albidum.,chop%2C%20and%20completely%20dry%20them."]'::jsonb, '["assets/images/sassafras-root-bark-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('rock-tripe-lichen', 'Rock tripe (lichen)', 'Rock tripe (lichen)', 'Mushroom', 'Emergency food when boiled and rinsed', 'Traditional source of vitamin C in survival situations', '', ARRAY['January','February','March','April','May','June','July','August','September','October','November','December']::text[], '[]'::jsonb, '["assets/images/rock-tripe-lichen-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('reindeer-lichen', 'Reindeer lichen', 'Reindeer lichen', 'Mushroom', 'Emergency survival flour after extensive prep', 'Poultice for wound care', '', ARRAY['January','February','March','April','May','June','July','August','September','October','November','December']::text[], '[]'::jsonb, '["assets/images/reindeer-lichen-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('maple-sap', 'Maple sap', 'Maple sap', 'Tree Product', 'Boiled into maple syrup or crystallized into sugar', 'Natural diuretic and energy tonic', '', ARRAY['March','April']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('birch-sap', 'Birch sap', 'Birch sap', 'Tree Product', 'Drank fresh or fermented into birch wine', 'Detoxifying diuretic', '', ARRAY['March','April']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('morel-mushrooms', 'Morel mushrooms', 'Morel mushrooms', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['April','May','June']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('black-morels', 'Black morels', 'Black morels', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['April','May','June']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('yellow-morels', 'Yellow morels', 'Yellow morels', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['April','May','June']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('spruce-gum', 'Spruce gum', 'Spruce gum', 'Tree Product', 'Chewed like natural chewing gum or infused into teas', 'Soothes sore throats; mild antiseptic', '', ARRAY['April','May']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('ramps-wild-onion', 'Ramps (Wild onion)', 'Ramps (Wild onion)', 'Root', 'Sautéed, pickled, or used in pesto like garlic', 'Digestive aid; antimicrobial', '', ARRAY['April','May']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('wild-leek-ramp', 'Wild Leek (Ramp)', 'Wild Leek (Ramp)', 'Root', 'Roasted, boiled, or dried and ground into flour; shoots eaten as vegetables', 'Rich in fiber and prebiotics; supports digestion', '', ARRAY['April','May']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('dandelion-greens', 'Dandelion greens', 'Dandelion greens', 'Green', 'Sautéed or in salads; bitter greens', 'Liver tonic; diuretic', '', ARRAY['April','May']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('chickweed', 'Chickweed', 'Chickweed', 'Green', 'Used fresh in salads or pesto', 'Anti‐inflammatory; skin healing', '', ARRAY['April','May']::text[], '["https://wildfoods4wildlife.com/monographs/common-chickweed/", "https://en.wikipedia.org/wiki/Stellaria_media"]'::jsonb, '["assets/images/chickweed-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('wood-sorrel', 'Wood sorrel', 'Wood sorrel', 'Green / Tubers', 'Tangy garnish in salads or soups, NA cooked it with sugar for dessert', 'High in vitamin C; digestive aide
Alleviates thirst
Aphrodisiac
alleviates mouth sores and sore throat
Helps with cramps, fever and nausea', '', ARRAY['April','May']::text[], '["https://en.wikipedia.org/wiki/Oxalis"]'::jsonb, '["assets/images/wood-sorrel-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('violet-leaves', 'Violet leaves', 'Violet leaves', 'Green', 'Steamed or added to salads', 'Expectorant; cough relief', '', ARRAY['April','May']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('plantain-broadleaf', 'Plantain (broadleaf)', 'Plantain (broadleaf)', 'Green', 'Cooked or used raw like lettuce
seeds a source of psyllium', 'Wound poultice; 
anti‐inflammatory;
analgesic
Skin diseases
respiritory problems', '', ARRAY['April','May']::text[], '[]'::jsonb, '["assets/images/plantain-broadleaf-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('miner-s-lettuce-winter-purslane', 'Miner''s lettuce | Winter Purslane', 'Miner''s lettuce', 'Green', 'Used raw in salads for mild flavor', 'High in vitamins; hydrating', 'can occasionally build up dangerous amounts of sodium oxalate (as can spinach)', ARRAY['April','May']::text[], '[]'::jsonb, '["assets/images/miner-s-lettuce-winter-purslane-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('dandelion-flowers', 'Dandelion flowers', 'Dandelion flowers', 'Flower', 'Fritters, syrups, or infused in honey', 'Liver support; antioxidant', '', ARRAY['April','May']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('violet-flowers', 'Violet flowers', 'Violet flowers', 'Flower', 'Candied or in syrups', 'Respiratory soother; mild expectorant', '', ARRAY['April','May']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('spruce-tips', 'Spruce tips', 'Spruce tips', 'Tree Product', 'Used fresh in syrups, teas, and baked goods', 'High in vitamin C; digestive aid', '', ARRAY['May','June']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('hemlock-tips', 'Hemlock tips', 'Hemlock tips', 'Tree Product', 'Infused in teas for a citrusy flavor', 'Rich in vitamin C; antimicrobial', '', ARRAY['May','June']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('wild-ginger', 'Wild ginger', 'Wild ginger', 'Root', 'Used as a ginger substitute in teas and cooking', 'Digestive aid; anti‐inflammatory', '', ARRAY['May','June']::text[], '[]'::jsonb, '["assets/images/wild-ginger-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('sweet-cicely', 'Sweet cicely', 'Sweet cicely', 'Root', 'Used fresh as sweetener or in salads', 'Digestive aid; carminative', 'Do not confuse with poison hemlock!!!', ARRAY['May','June']::text[], '["https://iowaherbalist.com/2014/09/25/licorice-of-the-woods/"]'::jsonb, '["assets/images/sweet-cicely-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('nettles', 'Nettles', 'Nettles', 'Green', 'Cooked like spinach or steeped as tea', 'Anti‐inflammatory; joint support', '', ARRAY['May','June']::text[], '["https://oaklandcountyblog.com/2014/05/14/foraging-for-stinging-nettle-just-dont-eat-it-raw/", "https://freshwater-reporter.com/stinging-nettle-friend-not-foe/"]'::jsonb, '["assets/images/nettles-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('red-sorrel', 'Red Sorrel', 'Red Sorrel', 'Green', 'Used raw in salads or soups for tangy flavor', 'Mild diuretic; antioxidant', '', ARRAY['May','June']::text[], '[]'::jsonb, '["assets/images/red-sorrel-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('wood-sorrel-yellow-woodsorrel', 'Wood Sorrel | Yellow Woodsorrel', 'Wood Sorrel', 'Green', 'Used raw in salads or soups for tangy flavor', 'Mild diuretic; antioxidant', '', ARRAY['May','June']::text[], '[]'::jsonb, '["assets/images/wood-sorrel-yellow-woodsorrel-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('lamb-s-quarters', 'Lamb''s quarters', 'Lamb''s quarters', 'Green', 'Cooked like spinach or added to soups', 'High in vitamins A and C; digestive aid', '', ARRAY['May','June']::text[], '[]'::jsonb, '["assets/images/lamb-s-quarters-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('goosefoot-close-cousin-of-lamb-s-quarters', 'Goosefoot | close cousin of lamb''s quarters', 'Goosefoot', 'Green', 'Cooked or raw like spinach', 'Nutrient‐rich greens; supports overall health', '', ARRAY['May','June']::text[], '["https://wildfoodgirl.com/2014/seed-sprouting-with-quinoas-wild-kin/"]'::jsonb, '["assets/images/goosefoot-close-cousin-of-lamb-s-quarters-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('wild-mustard-greens', 'Wild mustard greens', 'Wild mustard greens', 'Green', 'Sautéed or used in pesto', 'Digestive stimulant; anti‐inflammatory', '', ARRAY['May','June']::text[], '[]'::jsonb, '["assets/images/wild-mustard-greens-1.jpg", "assets/images/wild-mustard-greens-2.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('garlic-mustard', 'Garlic mustard', 'Garlic mustard', 'Green', 'Cooked like mustard greens; pungent flavor', 'Antimicrobial; digestive aid', '', ARRAY['May','June']::text[], '[]'::jsonb, '["assets/images/garlic-mustard-1.jpg", "assets/images/garlic-mustard-2.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('fiddlehead-ferns', 'Fiddlehead ferns', 'Fiddlehead ferns', 'Green', 'Sautéed or steamed; crisp texture', 'Antioxidant; nutrient‐dense', '', ARRAY['May','June']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('cattail-pollen', 'Cattail pollen', 'Cattail pollen', 'Flower', 'Infused into teas, syrups, or used as edible garnishes and candied petals', 'Contain flavonoids and antioxidants; soothing for respiratory health', '', ARRAY['May','June']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('cattail-shoots', 'Cattail shoots', 'Cattail shoots', 'Root', 'Eaten raw like asparagus or cooked in stews', 'Demulcent; soothes mucous membranes', '', ARRAY['May']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('juneberries-serviceberries', 'Juneberries (Serviceberries)', 'Juneberries (Serviceberries)', 'Fruit', 'Excellent in pies, jams, baked goods', 'High in antioxidants; digestive support', '', ARRAY['June','July']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('wild-strawberries', 'Wild strawberries', 'Wild strawberries', 'Fruit', 'Fresh eating; jams', 'Leaves tea for digestion', '', ARRAY['June','July']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('thimbleberries', 'Thimbleberries', 'Thimbleberries', 'Fruit', 'Jams; jellies', 'Soothes sore throats', '', ARRAY['June','July']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('yellow-pond-lily-bulbs', 'Yellow pond lily bulbs', 'Yellow pond lily bulbs', 'Root', 'Roasted or boiled; edible starch source', 'Used in poultices for skin ailments', '', ARRAY['June','July']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('purslane', 'Purslane', 'Purslane', 'Green', 'Eaten raw in salads or cooked; mucilaginous', 'Rich in omega‐3 fatty acids; diuretic', '', ARRAY['June','July']::text[], '[]'::jsonb, '["assets/images/purslane-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('clover-flowers', 'Clover flowers', 'Clover flowers', 'Flower', 'Tea, jellies, or salad garnish', 'Blood purifier; supportive during menstruation', '', ARRAY['June','July']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('honeysuckle-flowers', 'Honeysuckle flowers', 'Honeysuckle flowers', 'Flower', 'Infused in teas or syrups', 'Anti‐inflammatory; cold remedy', '', ARRAY['June','July']::text[], '["https://www.honey-plants.com/calendar/michigan/northern-bush-honeysuckle/"]'::jsonb, '["assets/images/honeysuckle-flowers-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('elderflowers', 'Elderflowers', 'Elderflowers', 'Flower', 'Fritters, teas, or cordial', 'Respiratory support; anti‐inflammatory', '', ARRAY['June','July']::text[], '[]'::jsonb, '["assets/images/elderflowers-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('chicory-flowers', 'Chicory flowers', 'Chicory flowers', 'Flower', 'Tea and coffee flavoring', 'Digestive aid; liver support', '', ARRAY['June','July']::text[], '["https://oaklandcountyblog.com/2020/08/14/chicory-queen-of-the-roadside/"]'::jsonb, '["assets/images/chicory-flowers-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('basswood-linden-flowers', 'Basswood (linden) flowers', 'Basswood (linden) flowers', 'Flower', 'Tea for relaxation', 'Calming; supports nervous system', '', ARRAY['June','July']::text[], '[]'::jsonb, '["assets/images/basswood-linden-flowers-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('pin-cherries', 'Pin cherries', 'Pin cherries', 'Fruit', 'Preserves, pies, wine', 'Anti-inflammatory; arthritis relief', '', ARRAY['June']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('blueberries', 'Blueberries', 'Blueberries', 'Fruit', 'Muffins; smoothies; jams', 'Eye & heart health', '', ARRAY['July','August']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('raspberries', 'Raspberries', 'Raspberries', 'Fruit', 'Fresh; sauces; desserts', 'Menstrual support tea', '', ARRAY['July','August']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('black-raspberries', 'Black raspberries', 'Black raspberries', 'Fruit', 'Syrups; pies', 'Immune support', '', ARRAY['July','August']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('huckleberries', 'Huckleberries', 'Huckleberries', 'Fruit', 'Pies; jams', 'Urinary tract health', '', ARRAY['July','August']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('gooseberries', 'Gooseberries', 'Gooseberries', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['July','August']::text[], '["https://honest-food.net/wild-gooseberries-edible/"]'::jsonb, '["assets/images/gooseberries-1.jpg", "assets/images/gooseberries-2.jpg", "assets/images/gooseberries-3.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('red-currants', 'Red currants', 'Red currants', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['July','August']::text[], '[]'::jsonb, '["assets/images/red-currants-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('black-currants', 'Black currants', 'Black currants', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['July','August']::text[], '[]'::jsonb, '["assets/images/black-currants-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('bearberries', 'Bearberries', 'Bearberries', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['July','August']::text[], '[]'::jsonb, '["assets/images/bearberries-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('mulberries', 'Mulberries', 'Mulberries', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['July','August']::text[], '["https://www.annarbor.com/entertainment/food-drink/wildcrafting-mulberries-are-suddenly-ripe-and-ready-to-be-enjoyed/"]'::jsonb, '["assets/images/mulberries-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('daylily-flowers', 'Daylily flowers', 'Daylily flowers', 'Flower', 'Fried or used in salads', 'Mild diuretic; edible petals', '', ARRAY['July','August']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('bee-balm-wild-bergamot', 'Bee Balm (wild bergamot)', 'Bee Balm (wild bergamot)', 'Flower', 'Tea or garnish; aromatic', 'Digestive tonic; antiviral', '', ARRAY['July','August']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('chanterelles', 'Chanterelles', 'Chanterelles', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['July','August']::text[], '["https://mynorth.com/2014/09/chanterelles-in-michigans-north-woods/"]'::jsonb, '["assets/images/chanterelles-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('russulas-edible-species-many-varieties-colors', 'Russulas  | (edible species) | Many varieties/colors', 'Russulas ', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['July','August']::text[], '["https://mushroomexpert.com/russula_vinacea.html"]'::jsonb, '["assets/images/russulas-edible-species-many-varieties-colors-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('chicken-of-the-woods', 'Chicken of the woods', 'Chicken of the woods', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['July','August']::text[], '["https://oaklandcountyblog.com/2021/09/24/the-hunt-is-on-chicken-of-the-woods/"]'::jsonb, '["assets/images/chicken-of-the-woods-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('black-trumpet', 'Black trumpet', 'Black trumpet', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['July','August']::text[], '["https://michpics.wordpress.com/2013/08/13/know-your-michigan-mushrooms-black-trumpet/"]'::jsonb, '["assets/images/black-trumpet-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('meadow-mushroom', 'Meadow mushroom', 'Meadow mushroom', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', 'Can be difficult to identify but good', ARRAY['July','August']::text[], '["https://www.mushroom-appreciation.com/meadow-mushroom.html"]'::jsonb, '["assets/images/meadow-mushroom-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('chokeberry-aronia', 'Chokeberry (Aronia)', 'Chokeberry (Aronia)', 'Fruit', 'Juiced or made into jams and syrups', 'High in antioxidants; supports cardiovascular health', '', ARRAY['July','August']::text[], '["https://www.canr.msu.edu/news/aronia_berries_1"]'::jsonb, '["assets/images/chokeberry-aronia-1.jpg", "assets/images/chokeberry-aronia-2.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('dewberries-very-similiar-to-blackberry', 'Dewberries | VERY similiar to blackberry', 'Dewberries', 'Fruit', 'Eaten fresh or in baked goods', 'Rich in vitamins; mild astringent', '', ARRAY['July','August']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('wild-blackberries', 'Wild blackberries', 'Wild blackberries', 'Fruit', 'Cobblers; jams', 'Digestive remedy', '', ARRAY['August','September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('chokecherries', 'Chokecherries', 'Chokecherries', 'Fruit', 'Syrups; wine; tinctures', 'Astringent; respiratory aid', '', ARRAY['August','September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('elderberries', 'Elderberries', 'Elderberries', 'Fruit', 'Syrups; cordials', 'Cold & flu relief', '', ARRAY['August','September']::text[], '[]'::jsonb, '["assets/images/elderberries-1.jpg", "assets/images/elderberries-2.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('ground-cherries', 'Ground cherries', 'Ground cherries', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['August','September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('riverbank-grapes', 'Riverbank grapes', 'Riverbank grapes', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['August','September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('wild-plums', 'Wild plums', 'Wild plums', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['August','September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('wintergreen-berries', 'Wintergreen berries', 'Wintergreen berries', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['August','September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('barberries', 'Barberries', 'Barberries', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['August','September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('fox-grapes', 'Fox grapes', 'Fox grapes', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['August','September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('staghorn-sumac-berries', 'Staghorn sumac berries', 'Staghorn sumac berries', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['August','September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('goldenrod-flowers', 'Goldenrod flowers', 'Goldenrod flowers', 'Flower', 'Tea or tincture for urinary tract support', 'Anti‐inflammatory; diuretic', '', ARRAY['August','September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('wild-hop-cones', 'Wild hop cones', 'Wild hop cones', 'Flower', 'Infused into teas, syrups, or used as edible garnishes and candied petals', 'Contain flavonoids and antioxidants; soothing for respiratory health', '', ARRAY['August','September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('boletes-porcini-some-varieties-good-some-poisonous', 'Boletes (porcini) | Some varieties good, some poisonous', 'Boletes (porcini)', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['August','September']::text[], '["https://boletes.wpamushroomclub.org/product-category/filter-set-1-regional-filters/zone-2-found-in-the-midwest/found-in-michigan/page/2/"]'::jsonb, '["assets/images/boletes-porcini-some-varieties-good-some-poisonous-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('king-bolete', 'King bolete', 'King bolete', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['August','September']::text[], '["https://practicalselfreliance.com/bolete-mushrooms/"]'::jsonb, '["assets/images/king-bolete-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('giant-puffball', 'Giant puffball', 'Giant puffball', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['August','September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('shaggy-mane', 'Shaggy mane', 'Shaggy mane', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['August','September']::text[], '["https://michpics.wordpress.com/2011/10/17/shaggy-mane-mushroom/"]'::jsonb, '["assets/images/shaggy-mane-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('hedgehog-mushrooms', 'Hedgehog mushrooms', 'Hedgehog mushrooms', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['August','September']::text[], '[]'::jsonb, '["assets/images/hedgehog-mushrooms-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('slippery-jack', 'Slippery jack', 'Slippery jack', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['August','September']::text[], '["https://boletes.wpamushroomclub.org/product/suillus-luteus/"]'::jsonb, '["assets/images/slippery-jack-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('yellowfoot-chanterelle', 'Yellowfoot chanterelle', 'Yellowfoot chanterelle', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['August','September']::text[], '[]'::jsonb, '["assets/images/yellowfoot-chanterelle-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('field-mushroom', 'Field mushroom', 'Field mushroom', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['August','September']::text[], '["https://www.first-nature.com/fungi/agaricus-campestris.php"]'::jsonb, '["assets/images/field-mushroom-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('lowbush-cranberries', 'Lowbush cranberries', 'Lowbush cranberries', 'Fruit', 'Sauces; relishes', 'Urinary tract support', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('highbush-cranberries-viburnum', 'Highbush cranberries | Viburnum', 'Highbush cranberries', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['September','October']::text[], '[]'::jsonb, '["assets/images/highbush-cranberries-viburnum-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('pawpaw', 'Pawpaw', 'Pawpaw', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('hawthorn-berries', 'Hawthorn berries', 'Hawthorn berries', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['September','October']::text[], '[]'::jsonb, '["assets/images/hawthorn-berries-1.jpg"]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('hazelnuts', 'Hazelnuts', 'Hazelnuts', 'Tree Product', 'Roasted or eaten raw; ground into nut butter', 'High in vitamin E; antioxidant support', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('beech-nuts', 'Beech nuts', 'Beech nuts', 'Tree Product', 'Roasted to remove bitterness; eaten as snack', 'Energy source; mild astringent', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('cattail-rhizomes', 'Cattail rhizomes', 'Cattail rhizomes', 'Root', 'Roasted, dried, and ground into flour', 'Poultice for wounds; skin soothing', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('burdock-root', 'Burdock root', 'Burdock root', 'Root', 'Cooked like a vegetable or used in stir‐fries', 'Blood purifier; diuretic', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('wild-carrot', 'Wild carrot', 'Wild carrot', 'Root', 'Eaten raw when young or cooked like carrots', 'Diuretic; supports digestion', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('groundnut-tubers', 'Groundnut tubers', 'Groundnut tubers', 'Root', 'Roasted or boiled; tastes like chestnut', 'Rich in protein and starch; energy source', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('oyster-mushrooms', 'Oyster mushrooms', 'Oyster mushrooms', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('hen-of-the-woods', 'Hen of the woods', 'Hen of the woods', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('lion-s-mane', 'Lion''s mane', 'Lion''s mane', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('cauliflower-mushroom', 'Cauliflower mushroom', 'Cauliflower mushroom', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('king-oyster', 'King oyster', 'King oyster', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('blewit-mushroom', 'Blewit mushroom', 'Blewit mushroom', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('crabapples', 'Crabapples', 'Crabapples', 'Fruit', 'Eaten fresh or made into cider and preserves', 'High in pectin; digestive aid', '', ARRAY['September','October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('larch-suillus', 'Larch suillus', 'Larch suillus', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['September']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('american-persimmon', 'American persimmon', 'American persimmon', 'Fruit', 'Eaten fresh or processed into pies, jams, jellies, and fruit butters', 'Rich in vitamins and antioxidants; supports immune health', '', ARRAY['October','November']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('jerusalem-artichoke', 'Jerusalem artichoke', 'Jerusalem artichoke', 'Root', 'Roasted or eaten raw; nutty flavor', 'Prebiotic inulin; supports gut health', '', ARRAY['October','November']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('chicory-root', 'Chicory root', 'Chicory root', 'Root', 'Roasted and ground as coffee substitute', 'Prebiotic; supports liver function', '', ARRAY['October','November']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('pine-nuts', 'Pine nuts', 'Pine nuts', 'Tree Product', 'Eaten raw or roasted; used in pestos', 'Rich in healthy fats; supports cardiovascular health', '', ARRAY['October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('acorns-leached', 'Acorns (leached)', 'Acorns (leached)', 'Tree Product', 'Leached to remove tannins, then ground into flour or roasted for a nutty snack', 'Astringent; used in poultices for minor skin irritations', '', ARRAY['October']::text[], '[]'::jsonb, '[]'::jsonb);

insert into public.upper_michigan_foraging_species_v1
  (species_slug, display_name, common_name, category, culinary_uses, medicinal_uses, notes, months_available, source_links, image_paths)
values
  ('velvet-foot', 'Velvet foot', 'Velvet foot', 'Mushroom', 'Sautéed, grilled, or added to stocks and soups for depth of flavor', 'Adaptogenic properties; supports immune function', '', ARRAY['October']::text[], '[]'::jsonb, '[]'::jsonb);
